name: build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04]
        include:
          - os: windows-2019
            platform: win
          - os: ubuntu-20.04
            platform: linux

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # not sure if we need libpcap to build for linux
      # users probably need to have it installed in their computer eitherway.
      - name: Install libpcap
        if: ${{ matrix.platform == 'linux' }}
        run: sudo apt-get install libpcap-dev -y

      - name: Install dependecies
        run: npm ci

      - name: Define next build version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --plugins '@semantic-release/npm'

      - name: Create executable
        run: npm run build -- --output ao-loot-logger-${{ matrix.platform }}

      - uses: actions/upload-artifact@main
        with:
          name: ao-loot-logger-${{ matrix.platform }}
          path: ao-loot-logger-${{ matrix.platform }}*
          if-no-files-found: error
